iteration 1 [Modifier Question language et Question type et ajour de …
hamzaoui-Hmz/Collaborative-exams pull request #11
Opened 2019-03-01 22:53 UTC by KatiaSersour

@oliviercailloux please review

2019-03-04 12:22 UTC, oliviercailloux requested changes
Approche générale ok. Encore quelques éléments à peaufiner.

2019-03-04 12:22 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/collaborative_exams/controller/ChangeQuestionLanguage.java
> +	public int getModifQuestionID(@FormParam("idQuestion") String idQuestion, @FormParam("newAuthorId") String newAuthorId, @FormParam("newAuthorId") String newLanguage, @CookieParam("authorId") Cookie
Certains de ces paramètres devraient être des `int`.

2019-03-04 12:22 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/collaborative_exams/controller/ChangeQuestionLanguage.java
> +		return Integer.valueOf(modifiedQuestion.getId());
Ceci ne retourne pas vraiment du JSON. On s’attend à une représentation JSON de la question si votre servlet renvoie du JSON. Ou le choix de type de retour n’est pas approprié : si vous voulez retourner simplement un int (ce qui me parait raisonnable), autant le retourner simplement comme un string. Le mieux serait de pouvoir retourner du JSON ou du text/plain à la demande.

2019-03-04 12:22 UTC, oliviercailloux commented on src/test/java/io/github/oliviercailloux/collaborative_exams/model/entity/QuestionTest.java
> +public class QuestionTest {
Tester les getter et setter n’est pas utile : c’est trop simple pour présenter un risque d’échec.
Par contre, il faut tester vos servlets.

2019-03-10 15:18 UTC, KatiaSersour commented on src/main/java/io/github/oliviercailloux/collaborative_exams/controller/ChangeQuestionLanguage.java
> +		return Integer.valueOf(modifiedQuestion.getId());
Cette méthode retourne l'ID de la question après modifications, j'ai choisi donc de le retourner simplement comme un String.

2019-03-10 15:20 UTC, KatiaSersour commented on src/main/java/io/github/oliviercailloux/collaborative_exams/controller/ChangeQuestionLanguage.java
> +	public int getModifQuestionID(@FormParam("idQuestion") String idQuestion, @FormParam("newAuthorId") String newAuthorId, @FormParam("newAuthorId") String newLanguage, @CookieParam("authorId") Cookie
Ok, commentaire pris en compte.

2019-03-11 09:54 UTC, KatiaSersour commented
@oliviercailloux please review 
Mon test unitaire sur le servlet n'est toujours pas opérationnel, je sens que je vais passer beaucoup de temps là-dessus. Je préfère avancer sur la 2eme itération et laisser les tests à la fin. Merci de votre compréhension.

2019-03-11 15:44 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/collaborative_exams/controller/ChangeQuestionLanguage.java
> +		return Integer.valueOf(modifiedQuestion.getId());
Oui, mais votre en-tête annonce que vous renvoyez du JSON, ce qui n’est pas vrai, comme vous l’admettez. De plus, ce serait plus élégant de renvoyer un int (puisque c’est un int) et de laisser JAX-RS convertir en String.

2019-03-11 15:47 UTC, oliviercailloux commented
En général, les fcts doivent être accompagnées de test, mais il est vrai que dans votre cas, il n’y a pas grand-chose de non trivial à tester unitairement. (Il faudrait plutôt des tests fonctionnels avec Arquillian par exemple, mais qu’on n’a pas vu.) Donc ok pour abandonner les tests. Veuillez effacer les tests qui ne testent que des getters, qui ne servent à rien.

Par contre, vos servlets devraient accepter en entrée des query parameters et non attendre un formulaire. Les requêtes avec des query parameters sont bien plus simples à façonner et à utiliser, et d’emploi plus courant.

2019-03-11 22:06 UTC, KatiaSersour commented
@oliviercailloux  please review

2019-03-11 22:07 UTC, KatiaSersour commented on src/main/java/io/github/oliviercailloux/collaborative_exams/controller/ChangeQuestionLanguage.java
> +		return Integer.valueOf(modifiedQuestion.getId());
En-tête corrigé.

2019-03-12 13:54 UTC, oliviercailloux commented
Il n’est plus vrai que vos servlets consomment du `MediaType.APPLICATION_FORM_URLENCODED`. Une fois ceci corrigé, vous pouvez fusionner sans redemander de review.

2019-03-12 13:54 UTC, oliviercailloux approved these changes

2019-03-12 17:42 UTC, merged