Mohamed it1
hamzaoui-Hmz/Collaborative-exams pull request #12
Opened 2019-03-02 20:25 UTC by hamzaoui-Hmz

@oliviercailloux please review

2019-03-04 12:44 UTC, oliviercailloux requested changes
Voir commentaires, et ajout de tests unitaires pour vérifier et documenter sérialisation et déserialisation.

2019-03-04 12:44 UTC, oliviercailloux commented on NewShemas.xsd
> +   <xsd:simpleType name="tag">
Je ne vois pas de raison de limiter les tags possibles. Ils devraient être libres. En outre, ils sont personnels, donc doivent être associés à une personne.
Je vous suggère de laisser cet aspect de côté pour le moment.

2019-03-04 12:44 UTC, oliviercailloux commented on pom.xml
> +  <groupId>com.google.code.gson</groupId>
Non, utiliser JSON-B comme demandé en cours.

2019-03-04 12:44 UTC, oliviercailloux commented on pom.xml
> +    <groupId>com.fasterxml.jackson.core</groupId>
Non, utiliser JAXB. (Ou préciser à quoi cela sert, si ce n’est pas remplaçable par JAXB.)

2019-03-04 12:44 UTC, oliviercailloux commented on pom.xml
> -        <finalName>${project.artifactId}</finalName>
Pourquoi retirez-vous ceci (finalName et plugin Surefire) ? Vous risquez de nuire à d’autres aspects du projet.

2019-03-04 12:44 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/collaborative_exams/helper/QuestionText.java
> +	public <T> List <String> ObjectListToJson(Class <T []> className) throws Exception{
Formatter le code.

Nom de la méthode et commentaire ne me semblent pas clairs : on s’attend à transformer une liste en json. Le contenu de la liste n’est pas clair non plus. Merci de réfléchir à une découpe en méthodes plus claire.

2019-03-04 12:44 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/collaborative_exams/helper/QuestionText.java
> +          e.printStackTrace();
Non. Jamais.

2019-03-04 12:44 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/collaborative_exams/helper/QuestionXml.java
> +			 * Creat marshaller context
Les commentaires de ce genre ne servent à rien, merci de les effacer.

2019-03-04 12:44 UTC, oliviercailloux commented on src/test/java/io/github/oliviercailloux/collaborative_exams/controller/GetQuestionTest.java
>  	public void getQuestionServletTest() throws Exception {
Ne faudrait-il pas invoquer quelque part votre servlet, dans votre `getQuestionServletTest` ?

2019-03-05 09:36 UTC, hamzaoui-Hmz commented on NewShemas.xsd
> +   <xsd:simpleType name="tag">
@oliviercailloux Merci de votre réponse. D'accord, je vais le corriger dans les brefs délais.

2019-03-05 09:38 UTC, hamzaoui-Hmz commented on pom.xml
> +  <groupId>com.google.code.gson</groupId>
@oliviercailloux . J'ai bien utilisé JsonB comme le cours. Ces dépendances ils ne sont pas utilisés. Ils seront supprimés dans le prochain commit

2019-03-05 09:39 UTC, hamzaoui-Hmz commented on pom.xml
> +    <groupId>com.fasterxml.jackson.core</groupId>
@oliviercailloux . J'ai utilisé JAXB comme vous l'avez demandé en cours. Ils seront supprimés dans le prochain commis

2019-03-05 09:40 UTC, hamzaoui-Hmz commented on pom.xml
> -        <finalName>${project.artifactId}</finalName>
@oliviercailloux . Je l'ai retiré par erreur. Je viens de corriger toutes les erreurs du pom et ils seront ajouter dans mon prochain commit

2019-03-05 09:40 UTC, hamzaoui-Hmz commented on src/main/java/io/github/oliviercailloux/collaborative_exams/helper/QuestionText.java
> +          e.printStackTrace();
@oliviercailloux Qu'entendez-vous exactement par "Non. Jamais. " ?  c'est par rapport à la méthode ou bien l'exception.

2019-03-05 16:42 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/collaborative_exams/helper/QuestionText.java
> +          e.printStackTrace();
Je faisais référence à la séance où j’ai lourdement insisté sur le fait de ne pas masquer les exceptions. Voir BP Exceptions.

2019-03-05 16:47 UTC, oliviercailloux commented
Voudriez-vous suivre les instructions en m’avertissant uniquement lorsque vous souhaitez une nouvelle review ? Ce qui ne semble pas être le cas en l’occurence, puisque je ne vois pas de commits suite à mes derniers commentaires.
Il ne faut certainement pas, au contraire, me mentionner à chaque réponse que vous me faites, une pratique qui produit l’effet inverse de celui cherché par les instructions (que je sois averti uniquement lorsqu’un nouvelle review est nécessaire) et en faveur de laquelle je ne parviens pas à imaginer la moindre raison.

2019-03-10 21:15 UTC, hamzaoui-Hmz commented
@oliviercailloux  please review
J'ai annulé la classe test pour cette itération. Il sera ajouté aux prochaines itérations.

2019-03-11 15:35 UTC, oliviercailloux commented
L’absence de tests ne me parait pas être une bonne idée. Il faut au contraire des tests accompagnants une fonctionnalité comme la vôtre, sinon la fct ne fournit aucune assurance qu’elle est développée convenablement et qu’elle le restera.
J’attends les tests adéquats pour une prochaine review.

2019-03-11 23:54 UTC, hamzaoui-Hmz commented
@oliviercailloux  please review
J'ai fait le test pour les différentes conversions de mes méthodes. Concernant le test de pour le servlet je préfère avancer sur la prochaine itération (2) et laisser les tests des servlets à la fin. Vu, à l'heure qu'il est et vu la complexité des tests en utilisant Arquillian va me faire passer beaucoup de temps dessus.

2019-03-12 13:56 UTC, oliviercailloux commented
Je parlais effectivement des tests de conversion et non des tests de servlet, il est vrai beaucoup plus compliqués et moins utiles.
Je ne review que quand il n’y a pas de conflits, à résoudre donc d’abord.

2019-03-12 17:55 UTC, hamzaoui-Hmz commented
@oliviercailloux please review

2019-03-13 09:39 UTC, oliviercailloux commented
Pour ne pas accroitre encore le retard important pris en itération 1, je propose de s’arrêter ici pour ce qui concerne cette fct. Vous pouvez donc la fusionner.

2019-03-13 09:39 UTC, oliviercailloux approved these changes

2019-03-13 09:51 UTC, merged