Valentin
hamzaoui-Hmz/Collaborative-exams pull request #14
Opened 2019-03-13 10:19 UTC by ducheminvalentin

PLEASE REVIEW @oliviercailloux .
Bonjour,
Il m'est vraiment difficile de travailler sur ce projet-là de part la difficulté à faire tourner le programme (ça n'a jamais marché chez moi en local, ni sur IBM Cloud) et de sa compréhension.
Quoi qu'il en soit, voilà mon PR pour ma seconde itération qui comprend la création d'un servlet ExportPDF qui permet d'exporter des questions sous forme d'examen écrit imprimable en PDF.

![examen](https://user-images.githubusercontent.com/32577978/54270858-a2256180-4580-11e9-9e70-bc70304b38c9.png)

Voilà à quoi ressemble l'examen lors de sa création. A noter que les champs " RECUPERATION QUESTIONS (1) seront remplacés par les données trouvées dans JPA Question phrasing vià la boucle 
`for (final Question question : listquestions) {

						Paragraph preface = new Paragraph("", titre);
					    PdfPTable table0 = new PdfPTable(3);
					    table0.setWidthPercentage(100);
					    table0.addCell(getCell(question.getPhrasing(), PdfPCell.ALIGN_LEFT));
					    document.add(table0);
					    addEmptyLine(preface, 3);
					    document.add(preface);
					}`

Par contre, j'ai une question à propos du chemin de téléchargement du fichier. Comment faire pour que le chemin soit générique pour tous les ordinateurs qui vont télécharger le pdf ? 
J'ai utilisé `private static String FILE = "src\\main\\Examen_.pdf" ;` pour qu'il me le mette à la racine de mon projet localement mais ça ne va pas fonctionner lorsqu'il sera sur IBM.
Dois-je mettre `String home = System.getProperty("user.home");
File file = new File(home+"/Downloads/Examen.pdf"); ` ?

Je me tiens à votre entière disposition pour discuter de mon PR.

Cordialement,
Valentin Duchemin

2019-03-15 09:13 UTC, oliviercailloux commented
Je ne trouve pas votre itération 1, l’ai-je validée ? À quelle PR correspond-elle ?
Vous avez raison de mentionner ce problème de programme non fonctionnel. Votre équipe aurait dû soulever ce problème et s’y attaquer sérieusement dès le départ, mais il n’est pas trop tard pour bien faire. Ajoutez une fct « restauration de l’exécutabilité » dans votre cahier des charges, chargez qqn de le faire dès que possible (vous ou qqn d’autre, à vous de décider ensemble), c’est plus urgent que tout le reste. Vous pouvez en contrepartie pousser qqch. en itération 3 au lieu de 2, ou abandonner une fct. À vous de décider ensemble. Je suis disposé à vous aider pour cette fct si elle vous semble difficile à réaliser, par e-mail ou en venant me voir à mon bureau.
Pour ce qui est de la compréhension de l’énoncé du projet, il faut également résoudre ce problème. Prenez r-v par e-mail pour venir me voir à mon bureau (avec d’autres membres de l’équipe si opportun) et on prendra le temps nécessaire. Ou posez vos questions par e-mail si vous pensez que je peux vous aider ainsi (mais ça risque d’être moins efficace). On peut aussi en discuter au téléphone.

2019-03-15 09:21 UTC, oliviercailloux requested changes
Votre servlet doit produire un flux binaire encodant le PDF. Donc au lieu de l’écrire sur le disque, il faut l’envoyer au client comme une réponse HTTP, répondant à la requête HTTP reçue par votre servlet. Il faut indiquer dans l’en-tête le type mime adéquat (définissant un PDF).

2019-03-15 09:21 UTC, oliviercailloux commented on pom.xml
> +		    <groupId>org.bouncycastle</groupId>
Je ne vois pas où vous l’utilisez pour le moment. Enlevez si inutile ou dites-moi où c’est utilisé.

2019-03-15 09:21 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/collaborative_exams/controller/ExportPdf.java
> +	        e.printStackTrace();
Non, ne pas masquer les exceptions.

2019-03-15 09:21 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/collaborative_exams/controller/ExportPdf.java
> +	    	System.out.println("Access Path" + FILE);
Formatter le code !

2019-03-15 09:24 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/collaborative_exams/controller/ExportPdf.java
> +	    	System.out.println("Access Path" + FILE);
Logger avec JUL comme vu au cours.

2019-03-15 09:25 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/collaborative_exams/controller/ExportPdf.java
> +	@Produces(MediaType.TEXT_PLAIN)
Votre servlet est annoncé comme produisant du TEXT_PLAIN, mais ce n’est pas vrai, il ne produit rien à l’heure actuelle (en ce qui concerne ce qu’il répond au client). Il doit plutôt produire du PDF.

2019-03-15 09:37 UTC, ducheminvalentin commented
Bonjour @oliviercailloux .
Merci pour vos précieux retours.

• Vous n'avez pas trouvé ma première itération car elle n'a pas encore été PR. Elle arrive bientôt.

• Certains arrivent à faire tourner le programme de base, d'autres non avec exactement le même code et les mêmes paramètres. Il doit s'agir d'un problème de configuration de l'IDE, de version de Maven, ou de serveurs (testés sous GlassFish, WildFly et IBM Cloud) que j'essaie de résoudre depuis quelques mois. (A noter que ça marchait un jour sur ma machine). Dans tous les cas, je code sur un autre projet Servlet et lorsque ma fonctionnalité est correcte, je la push sur le code du projet de base en effectuant les modifications nécessaires avec l'implémentation de JPA.

• Merci de m'avoir éclairé sur le Servlet ExportPDF, je comprends mieux ce qu'il faut faire.

2019-03-15 09:58 UTC, oliviercailloux commented
Votre première itération était à rendre pour fin février. Vous êtes très en retard.
Je maintiens qu’il faut résoudre le problème, ce n’est pas une façon adéquate de fonctionner et de toute façon ça indique un problème de qualité de code qqpart.
Au fait, il n’est pas demandé d’exporter toutes les questions (pas très utile) mais bien un examen, soit un choix par l’utilisateur d’un sous-ensemble de questions.  Pour ce faire, il faut créer un objet Examination qui contient une liste de questions, et pouvoir le parser à partir de json, et votre servlet doit consommer un Examination. (Ça vous vaudra 1,75 pts de fct de faire tout ça convenablement.)

2019-03-15 10:00 UTC, oliviercailloux commented
Pour votre pbl de config sur votre machine, venez me voir et on cherchera ensemble. Il ne faut pas rester bloqué autant de temps sur un problème.

2019-03-15 10:09 UTC, ducheminvalentin commented
@oliviercailloux Je préfère me concentrer sur l'itération 2 actuellement qui peut elle au moins me rapporter quelques points. Mes deux itérations sont indépendantes, je n'ai pas besoin de terminer la première pour réussir la seconde.
Sachez également que j'ai essayé par tous les moyens de résoudre le problème de configurations. J'ai checké une multitude de sites différents sans aucune bonne réponse. Je vais essayer encore une fois aujourd'hui. Et si ça ne marche pas, j'essaierai de me libérer début de la semaine prochaine pour qu'on regarde ensemble sur ma machine. (Nous sommes encore en alternance la semaine prochaine).

Concernant l'objet Examination, mon collègue @boumaza-khaled doit également créer une partie Examen pour sa seconde itération, j'espère que nous n'allons pas coder la même chose des deux côtés.

2019-03-15 10:47 UTC, oliviercailloux commented
Concernant Examination : je ne sais pas, je n’ai pas fait attention à ça. À vous en tant que groupe de bien répartir les tâches. Vous pouvez très bien attendre qu’il ait fini, ou proposer de la faire à sa place et lui donner autre chose à faire. En tous cas, effectivement, il ne faut pas que vous codiez deux fois la même chose. Mais attention à livrer votre fct à temps !

2019-03-15 10:50 UTC, ducheminvalentin commented
@oliviercailloux C'est noté. 
Merci pour votre temps et votre implication en tout cas. En espérant que nos prochains livrables vous plaisent.

2019-03-18 15:08 UTC, ducheminvalentin commented
Bonjour @oliviercailloux PLEASE REVIEW.

**GetListExamenQuestion** contient 
• Une fonction **Examination** où l'utilisateur envoi les questions (En Json) qu'ils souhaitent avoir dans l'examen. Celles-ci sont stockées dans la variable listExamenQuestion.
• Une fonction givelistExamenQuestion() où la méthode va renvoyer en format pdf les questions qui est affiché dans le navigateur. Il aura possibilité d'imprimer le pdf s'il le souhaite.

• Concernant le problème de déploiement, j'ai remarqué qu'il se lance quand il le souhaite. C'est-à-dire je peux cliquer 45fois sur " Run as Server " sans rien qu'il se passe mais au 46ème, il se lancera. Lorsqu'il persiste à ne pas vouloir se lancer, je dois re-allumer Eclipse et faire toutes les MAJ.

2019-03-19 18:54 UTC, oliviercailloux requested changes

2019-03-19 18:54 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/collaborative_exams/controller/GetListExamenQuestion.java
> +	private static Font titre = new Font(Font.FontFamily.TIMES_ROMAN, 20, Font.BOLD);
Comme c’est une constante, déclarer avec final, et nommer en majuscules. Noms en anglais.

2019-03-19 18:54 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/collaborative_exams/controller/GetListExamenQuestion.java
> +	final List<Question> listExamenQuestion = null;
Ceci ne peut pas fonctionner, cette variable sera toujours `null` (puisque `final` et initialisée à `null`).

2019-03-19 18:54 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/collaborative_exams/controller/GetListExamenQuestion.java
> +	public Response Examination(JsonObject questionJson) throws Exception {
BP style. Éviter de balancer `Exception`, trop général, plutôt une exception en particulier ou mieux, `WebApplicationException` (cf. diapos cours).

2019-03-19 18:54 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/collaborative_exams/controller/GetListExamenQuestion.java
> +	// '{"id":"2"}' http://localhost:8080/examcollab/ExportPdf
Déplacer ce commentaire à un endroit où il est visible et censé, ou le supprimer.

2019-03-19 18:54 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/collaborative_exams/controller/GetListExamenQuestion.java
> +		listExamenQuestion.add(question);
Ce code ne peut pas fonctionner (cf. ci-dessus, cette liste est `null`), mais même en supposant qu’elle soit bien initialisée, la logique ne me semble pas valide, ou je ne la comprends pas. Tous les utilisateurs de votre serveur partagent le même examen, d’après vous ?

Il faut au contraire, et plus simplement, envoyer une liste de questions d’un coup (un examen, donc), en Json. Pour rappel, REST implique Stateless.

2019-03-19 18:54 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/collaborative_exams/controller/GetListExamenQuestion.java
> +		return Response.ok().entity("ok").encoding(MediaType.TEXT_PLAIN).build();
Inutile de renvoyer une `Response` qui dit toujours Ok, ne rien répondre est tout aussi informatif et plus simple. (Plus élégant serait de renvoyer une redirection, mais de toute façon ce n’est pas ce qui est demandé ici.)

2019-03-21 12:37 UTC, ducheminvalentin commented
Bonjour @oliviercailloux PLEASE REVIEW.

J'aimerais expliquer mes choix pour ce PR que j'espère sera validé.
Dans  
> Service.QuestionService.java

J'ai ajouté une fonction `findById` dans un premier temps avant que je m'aperçoive que la fonction `findQuestion` existait également. Elles font pratiquement la même chose mais j'ai "custom" en cas d'entité non trouvée pour ma propre fonction que je vais expliquer.

> controller.GetListExamenQuestion

Alors là, je ne suis pas très fière de ce que j'ai produit, mais ça devrait nous satisfaire. 
A la base, je voulais une méthode **@POST** qui prend en Json la liste des questions comme celui sur mon projet d'entraînement. (La balise Code ne fonctionne pas correctement, je mets ça sous quote)
>@POST
	@Consumes({MediaType.APPLICATION_JSON})
	public String createList(JsonObject commentJson) throws IOException {
		JsonArray jArray = commentJson.getJsonArray("list");
		for(int i=0; i < jArray.size(); i++) {
			  System.out.println("----");
			  System.out.println(jArray.get(i));
			  System.out.println(jArray.getInt(i));
			  System.out.println("----");
				 try {
			            // Find an entity that is not exists in the database will
			            // throw an exception.
					 Comment comment = commentService.findById(jArray.getInt(i));
					 System.out.println("Get Commentaire " + comment.getCommentary());
			        } catch (EntityNotFoundException e) {
			            e.getMessage();
			        }	
 }
		return "Voici les id des questions que vous souhaitez : " + jArray ;
}

Ce code présent marche avec le cURL: 
`curl --header "Content-Type: application/json" --data "{\"list\":[1,2] }" --request POST http://localhost:8080/jpa_ducheminvalentin/list`
Il va nous dire si l'entité id: 1 et l'entité id: 2 existent. Si oui, il nous retourne en Syso le Commentaire associé.

Cependant, pour la suite je voulais avoir un @GET qui retournait en @Produce("application/pdf") mon jArray (mettre une nouvelle boucle for pour la lire). Cependant je n'ai trouvé aucun moyen de passer cette donnée dans mon @GET hormis créer une nouvelle entité Examination auquel cas je persisterais mon jArray dans celle-ci et je demanderais la lecture dans le @GET mais c'était pas ce qui était demandé.


**Du coup, j'ai fait un mixte de @POST et @GET** où on récupère les données Json qui seront traités directement au moment de l'affichage dans le tableau (du pdf).
Chaque utilisateur passera les questions qu'ils souhaitent voir à l'examen.
Ma fonction `Question question = questionService.findById(jArray.getInt(i));` permettra de voir si les questions sont dans la base et si oui, alors on affichera `question.getPhrasing()` qui retournera l'intitulé de la question demandée. 

J'espère que mon PR pour cette itération n°2 sera validé. 
Bonne journée.

2019-03-22 10:42 UTC, oliviercailloux requested changes
Je ne comprends pas votre commentaire décrivant votre tentative initiale. Vous me montrez une méthode `createList(JsonObject commentJson)`, mais elle ne semble pas créer une liste, et son paramètre, me décrivez-vous, est une liste de question, alors que la méthode dit que c’est un commentaire. Je ne sais pas, en outre, ce qu’est un commentaire ou ce que fait commentService.

Quoi qu’il en soit, l’approche finalement adoptée correspond effectivement à ce qui est attendu, me semble-t-il.

Il faut découpler la logique de création du PDF, de parsing du json, et de récupération des questions depuis la base. Créer par exemple (entre autres) une méthode `asPdf(List<Question> questions)` et une méthode `asIds(JsonArray questionIdsJson): List<Integer>` et les combiner dans votre servlet.

Résoudre warnings Eclipse (cf. Tools.adoc).

Fournir un test unitaire qui envoie un json array et ouvre le PDF résultant et vérifie une partie de son contenu. (Inutile de tout vérifier, se contenter de vérifier que le PDF semble avoir le bon contenu.) Le test ne doit pas nécessairement utiliser Arquillian, on peut se contenter d’invoquer les méthodes adéquates classiquement. Il faut donc ne pas invoquer de méthodes qui cherchent dans la BD, dans le test, ce que la découpe suggérée ci-dessus permet.

2019-03-22 10:42 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/collaborative_exams/Service/QuestionService.java
> +	}
Malgré votre explication en commentaire de ce PR, je ne comprends pas l’intérêt de dupliquer cette méthode. Veuillez simplement modifier `findQuestion` pour qu’il renvoie l’exception que vous désirez (qui est effectivement un choix nettement meilleur). L’exception doit parler anglais.

2019-03-22 10:42 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/collaborative_exams/controller/GetListExamenQuestion.java
> +		JsonArray jArray = questionJson.getJsonArray("list");
Inutilement complexe. On s’attend à envoyer directement un JsonArray à votre servlet. Ce JsonArray contiendrait une liste de questions.
Votre en-tête devrait donc être : `public Response asPdf(JsonArray questionIdsAsJson) throws …`

2019-03-26 18:37 UTC, ducheminvalentin commented
@oliviercailloux 
Bonjour, voici la liste des changements:

- Decouplage de la fonction GetListExamen Question : 
1. Création d'une méthode asPdf(JsonArray questionIdsAsJson) prenant en paramètre JsonArray.
2. Création d'une méthode createTitleDocument() reprenant le code de création du pdf.
3. Création d'une méthode createBodyDocument(questionIdsAsJson) prenant en paramètre JsonArray permettant de l'intégrer dans le document.
- Changement de la fonction findQuestion.
1. Suppression de la fonction doublon. 
2. Modification de la fonction originale. 
3. L'exception parle anglais.

- Résolution du Warning Eclipse suivant votre tutoriel.

J'espère que mon PR pour cette itération n°2 sera validé.
Bonne journée.

2019-03-27 17:47 UTC, oliviercailloux requested changes
Je ne vois pas de test unitaire.

2019-03-27 17:47 UTC, oliviercailloux commented on Eclipse-prefs.epf
> +file_export_version=3.0
Inutile d’inclure ce fichier à votre projet.

2019-03-27 17:47 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/collaborative_exams/Service/QuestionService.java
> +	public Question findQuestion(Integer id) {
Le paramètre devrait être de type primitif int (comme avant), qui évite les entrées null non souhaitées ici.

2019-03-27 17:47 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/collaborative_exams/Service/QuestionService.java
> +					"Unable to find valid id :  " + id + ". Please, make a new request with valid id.");
(Détail) ‘Unable to find id:’, pas valid id.

2019-03-27 17:47 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/collaborative_exams/controller/GetListExamenQuestion.java
> +public class GetListExamenQuestion {
Indiquer explicitement que ce servlet est censé être instancié pour une seule requête avec une annotation RequestScoped, c’est important ici.

2019-03-27 17:47 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/collaborative_exams/controller/GetListExamenQuestion.java
> +				e.getMessage();
Non, ne pas masquer les exceptions. BP Exceptions.

2019-03-27 17:47 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/collaborative_exams/controller/GetListExamenQuestion.java
> +
Ce code ne peut pas fonctionner, document est null car non initialisé avant son premier usage. Avez-vous testé le code ?

2019-03-27 20:40 UTC, ducheminvalentin commented
Bonjour @oliviercailloux 

> Je ne vois pas de test unitaire.

Je n'ai pas les compétences nécessaires pour effectuer un bon test unitaire. Je préfère me concentrer sur la fonction principale pour valider cette seconde itération.
> Inutile d’inclure ce fichier à votre projet.

Je pensais que c'était important de l'ajouter puisque les autres du groupe (et peut-être des suivants) auront le fichier de configuration d'Eclipse directement en place pour le projet.

>Le paramètre devrait être de type primitif int (comme avant), qui évite les entrées null non souhaitées ici.

Vous avez raison. Le soucis a été corrigé.

>(Détail) ‘Unable to find id:’, pas valid id.

Votre anglais est meilleur que le mien, je vous fais confiance.

> Indiquer explicitement que ce servlet est censé être instancié pour une seule requête avec une annotation RequestScoped, c’est important ici.

Vous avez également raison. J'ai ajouté l'annotation.

> Non, ne pas masquer les exceptions. BP Exceptions.

Après réflexion, il est préférable de ne pas masquer cette exception, effectivement. 

> Ce code ne peut pas fonctionner, document est null car non initialisé avant son premier usage. Avez-vous testé le code ?

Comme dit précédemment, le projet ne marche pas à chaque fois. Selon les experts de la classe en JEE, il s'agit d'un problème de permissivité entre les différents serveurs et différentes versions. Certains serveurs comme Tomcat sont beaucoup moins exigeants (ils laissent passer des erreurs à la compilation) à contrario de GlassFish ou WildFly (versions récentes) qui relèvent l'erreur et retourne une erreur.

Ainsi, je développe mes servlets sur un environnement stable et lorsque mes servlets fonctionnent, je les envois sur le projet en faisant les dernières configurations. Cependant, il m'arrive de modifier dans les dernières minutes deux trois petites choses sans faire attention au code dans son ensemble.

J'espère que ce PR sera validé. 

Merci et bonne soirée.

2019-03-27 21:34 UTC, oliviercailloux commented
J’insiste pour le test unitaire. Une telle fct sans test unitaire perd énormément de valeur. Le test unitaire fait partie de la fct principale, ce n’est pas un plus. Il ne requiert pas de compétences importantes que vous n’auriez pas, je pense que vous vous sous-estimez. Suivre le tutoriel indiqué en cours suffit pour savoir comment en écrire, et pour le reste, c’est du Java normal.

Avez-vous maintenant testé le code sur votre environnement de développement ?

2019-03-27 22:34 UTC, ducheminvalentin commented
@oliviercailloux 
Non, je ne peux pas faire ce test unitaire. J'ai beaucoup de difficulté à coder la moindre chose sur ce projet, et je vais en avoir 2x plus pour coder des tests unitaires. j'ai du passer 140 heures pour le développement de cette seconde itération, j'ai passé 140 heures à échouer. Ça parait aberrant comme nombre d'heures mais quand les environnements sont instables, peu fiables et qu'il faut implémenter des méthodes "les yeux fermés", ça complique beaucoup de choses. J'étais partisan pour repartir d'un projet FromScratch mais ce n'était pas l'avis de tout le monde. 
Alors je me résigne à faire ce que je peux. C'est-à-dire coder petit à petit et corriger, pour la unième fois les erreurs et problèmes que vous soulevez.
Je n'ai ni la capacité pour faire ce test unitaire, ni le moral actuellement car ce projet m'enfonce petit à petit dans la déprime et je ne suis pas le seul.

Alors sans ce testUnitaire, j'espère que mon PR soit validé. 

Merci et bonne soirée.

2019-03-28 10:42 UTC, oliviercailloux commented
Je comprends mieux, ce n’est pas un problème de compétences mais un problème de motivation et de gestion de projet. Je pense que nous allons trouver une solution en discutant ensemble en séance. Pour le moment, j’accepte la fct en l’état. Il faut noter dans le cahier des charges qu’il faut ajouter un test à la prochaine itération.

2019-03-28 15:16 UTC, oliviercailloux approved these changes

2019-03-28 15:16 UTC, merged