Fonctionnalité 2 Question multi-format
hamzaoui-Hmz/Collaborative-exams pull request #15
Opened 2019-03-13 15:12 UTC by KatiaSersour

@oliviercailloux  please review

2019-03-15 10:10 UTC, oliviercailloux requested changes
Formatter code.
Résoudre warnings vus par Eclipse (cf Tools.adoc).
Éviter le type général `Exception` utiliser des types plus spécifiques (ici `IllegalArgumentException` par exemple).

2019-03-15 10:10 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/collaborative_exams/controller/QuestionMultiFormat.java
> +		if (format == "Json")
Non, utiliser le mécanisme de JAX-RS de sélection du format à renvoyer vu au cours.

2019-03-15 10:10 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/collaborative_exams/controller/QuestionMultiFormat.java
> +	@Produces(MediaType.TEXT_PLAIN)
Ce n’est pas vrai, votre servlet produit du Json ou du XML, mais jamais du plain.

2019-03-15 10:20 UTC, oliviercailloux commented
Veuillez par ailleurs utiliser la fct d’export en XML produite en PR #12 en l’adaptant éventuellement à vos besoins. (Je ne sais pas pourquoi certaines de ces classes, telle que `helper/QuestionXML`, ont disparu de la branche master mais il faut j’imagine les y remettre avec votre PR.)

2019-03-16 16:07 UTC, KatiaSersour commented
@oliviercailloux please review.
Concernant le type d'exception, il y a des endroits où je ne peux pas le modifier en  IllegalArgumentException, parce que je risque d'avoir des erreurs sur ma première itération et les itérations des autres membres du groupe. Merci pour vos retours.

2019-03-17 08:49 UTC, oliviercailloux requested changes
Utilisation toujours incorrecte de JAX-RS. Le client HTTP est supposé préciser le format dans l’en-tête approprié, voir cours HTTP.adoc. Revoir aussi cours sur JAX-RS ou ressources indiquées dans le cours pour plus de détails.

Concernant les exceptions, je ne comprends pas votre réponse. En quoi l’utilisation de `IllegalArgumentException` au lieu du type général `Exception` pourrait nuire ? Pouvez-vous me donner un exemple précis ?

Vous pouvez aussi, et ce serait même mieux en fait, renvoyer plutôt une `WebApplicationException` comme suggéré en cours.

2019-03-17 09:43 UTC, KatiaSersour commented
@oliviercailloux merci pour votre réponse.
Exemple pour mieux expliquer ma réponse concernant les exceptions:
Mon servlet fait appel à la méthode **findQuestion(int id)**  de la classe **QuestionService** qui lance une exception de type **Exception**

2019-03-17 10:29 UTC, oliviercailloux commented
> @oliviercailloux merci pour votre réponse.
> Exemple pour mieux expliquer ma réponse concernant les exceptions:
> Mon servlet fait appel à la méthode **findQuestion(int id)** de la classe **QuestionService** qui lance une exception de type **Exception**

1. Cela ne vous empêche pas de changer votre autre `throw new Exception`. (Comme vous avez correctement fait à un autre endroit.)
2. C’est une erreur dans `findQuestion` qui m’a échappé. Vous pouvez utiliser un try-catch pour envoyer plutôt une exception de type WebApplicationException comme suggéré, ce sera plus propre. L’exception originale doit se retrouver dans la nouvelle (utiliser le constructeur approprié). Si vous ne voyez pas comment faire, laissez tomber cet aspect.

2019-03-18 14:24 UTC, KatiaSersour commented
@oliviercailloux please review
J'ai utilisé le Accept header que le client spécifiera. JAX RS convertira directement l'entité Question renvoyée dans le format souhaité par le client. Donc le paramètre QueryParam("format") n'est plus utile.

2019-03-19 18:59 UTC, oliviercailloux approved these changes
Voilà un code simple et élégant.
Détail : supprimer ligne blanche entre en-tête méthode et annotation Jax-rs. Fusionner ensuite.

2019-03-19 19:23 UTC, merged