Mohamed it2
hamzaoui-Hmz/Collaborative-exams pull request #16
Opened 2019-03-13 22:57 UTC by hamzaoui-Hmz

@oliviercailloux  please review
Il s'agit de la deuxième fonctionnalité

2019-03-15 09:50 UTC, oliviercailloux requested changes
Commentaire général : évitez de renvoyer comme exception le type général `Exception`, utilisez qqch. de plus particulier en fonction des circonstances (voir Contrat/presentation dans cours).

2019-03-15 09:50 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/collaborative_exams/Service/PersonService.java
>  		return results.get(0);
Pas très sympa de lancer une exception quand l’e-mail ne correspond à rien : l’utilisateur de cette classe n’a pas de moyen simple de le savoir. Mieux vaudrait renvoyer un Optional<Person>. (BP null.)

2019-03-15 09:50 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/collaborative_exams/Service/PersonService.java
> +	public boolean deletAllPerson() throws Exception{
`deleteAllPersons()`

2019-03-15 09:50 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/collaborative_exams/Service/PersonService.java
> +		}else{
Formatter le code !

2019-03-15 09:50 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/collaborative_exams/Service/PersonService.java
> +		    Person PersonDeleted =em.merge(p);
Respecter les conventions de nommage SVP.

2019-03-15 09:50 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/collaborative_exams/Service/PersonService.java
> +		return true;
`return query.isEmpty()`, vous voulez dire ?

2019-03-15 09:50 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/collaborative_exams/Service/PersonService.java
> +		}
Tout ça est bien trop complexe. Utiliser simplement une requête pour effacer tout (DELETE au lieu de SELECT) !

2019-03-15 09:50 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/collaborative_exams/Service/PersonService.java
> +		em.merge(personResult);
Inutile, personResult est dans le contexte de persistence après le find.

2019-03-15 09:50 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/collaborative_exams/Service/QuestionService.java
> +	public List<Question> findPersonQuestion(Person pers) throws Exception {
questions, au pluriel.

2019-03-15 09:50 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/collaborative_exams/controller/DeletPerson.java
> +	@Produces(MediaType.TEXT_PLAIN)
Ce n’est pas vrai, votre servlet ne consomme ni ne produit quoi que ce soit.

2019-03-15 09:50 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/collaborative_exams/controller/DeletPerson.java
> +		return Response.ok(Response.Status.OK).build();
Autant ne rien renvoyer, le conteneur s’en charge.

2019-03-15 09:50 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/collaborative_exams/controller/DeletPerson.java
> +		throw new Exception("Questions is not deleted from DB");
Mieux vaudrait simplement laisser une exception éventuelle se propager depuis la méthode `deleteAllPersons`.

2019-03-15 11:03 UTC, hamzaoui-Hmz commented on src/main/java/io/github/oliviercailloux/collaborative_exams/Service/PersonService.java
> +		}else{
@oliviercailloux merci de votre réponse

Pourquoi dois-je formater le code ?

En fait, je vérifie d'abord si la personne n'a aucune question alors dans ce cas je supprime que la personne. Dans le cas contraire, si la personne a plusieurs questions alors dans ce cas je supprime d'abord les questions qui sont créées par ce dernier et ensuite je supprime la personne.

2019-03-15 11:04 UTC, hamzaoui-Hmz commented on src/main/java/io/github/oliviercailloux/collaborative_exams/Service/PersonService.java
> +		return true;
@oliviercailloux 
Elle permet de vérifier si la personne est bien supprimée dans la base de données et Le résultat est récupéré par la servlet DeletPerson

2019-03-15 11:32 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/collaborative_exams/Service/PersonService.java
> +		}else{
Il faut toujours formatter le code. Ça le rend plus facile à lire ; évite les erreurs (une mauvaise indentation peut induire en erreur concernant la structure des instructions conditionnelles) ; permet à git de s’y retrouver.

Il vaut mieux laisser faire JPA en utilisant le mécanisme de cascade, dans ce cas.
Mais il vaudrait mieux interdire la suppression d’une question. Il faut que les utilisateurs puissent compter sur la pérennité des questions.

2019-03-16 23:02 UTC, hamzaoui-Hmz commented
@oliviercailloux please review

2019-03-17 11:42 UTC, oliviercailloux commented
Veuillez remettre un code formaté correctement. Je reviewerai quand ce sera le cas.
Par ailleurs, le servlet SameAbility ne sert pas à grand-chose tant que la fonctionnalité same ability n’est pas implémentée correctement. Pour le moment il ne semble pas possible d’indiquer que deux questions interrogent sur la même "ability".
Veuillez réfléchir à et me décrire votre objectif précisément pour cette fct.

2019-03-19 21:28 UTC, hamzaoui-Hmz commented
@oliviercailloux  please review 
J'ai formaté le code et supprimé la servlet GetAbility (elle sera ajoutée quand @boukalaamine va implémenter sameAbility dans la prochaine itération). De plus, j'ai modifié PersonnalTag avec l'ajout d'une servlet SetTag

2019-03-20 07:25 UTC, oliviercailloux commented
Comme j’écrivais : « Veuillez réfléchir à et me décrire votre objectif précisément pour cette fct. »
Veuillez modifier le README (dans cette même PR) pour y inclure cette description à la place des trois boulettes actuelles.

2019-03-20 09:15 UTC, hamzaoui-Hmz commented
@oliviercailloux please review 

Je viens de modifier le cahier de charge. Il s'agit du déplacement de getAbility dans troisième itération en attendant la création de samAbility par Amine.

Concernant l'objectif de cette itération est d'améliorer la création d'un PersnnelTag et l'ajout d'un servlet Set pour ce dernier. De plus, implémenter un servlet getPerson et servlet qui permet de supprimer les données dans la BD ( les questions, les personnes ... )

2019-03-21 08:13 UTC, oliviercailloux commented
Comme j’écrivais : « Veuillez réfléchir à et me décrire votre objectif précisément pour cette fct. »
Veuillez modifier le README (dans cette même PR) pour y inclure cette description à la place des trois boulettes actuelles.

2019-03-21 09:14 UTC, hamzaoui-Hmz commented
@oliviercailloux please review
 J'ai mis à jour le REDAME. Je crois que je suis précis concernant les objectifs de cette fnct ?.
j'ai gardé les mêmes tâches qu'avant avec l'ajout d'une tâche qui est d'améliorer le PersonalTag et l'ajout d'un servlet Set pour le PersonalTag

2019-03-21 18:01 UTC, oliviercailloux requested changes
Je n’ai pas l’impression que toutes mes remarques précédentes aient été prises en compte.

2019-03-21 18:01 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/collaborative_exams/controller/NewPersonTag.java
> +	public String newPersonTag(MultivaluedMap<String, String> form, @CookieParam("authorId") Cookie cookie)
Éviter les FORM en entrée, pratiques uniquement pour les formulaires HTML. Préférer des vrais paramètres de requêtes, plus indépendants du langage.

2019-03-21 18:01 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/collaborative_exams/controller/GetPerson.java
> +		return result;
Renvoyer SVP du JSON valide. Ceci ne produira pas du JSON valide dans le cas de plus d’un élément. Il faut sérialiser la liste de personnes en JSON.

2019-03-21 23:43 UTC, hamzaoui-Hmz commented
@oliviercailloux  please review 
J'ai pris en compte tout vos commentaires.

2019-03-22 12:33 UTC, oliviercailloux commented
Il faut encore un test unitaire pour vérifier et documenter l’obtention d’une liste de personnes au format Json.

2019-03-22 18:00 UTC, hamzaoui-Hmz commented
@oliviercailloux  please review 
Je peux  faire le merge dans master ?

2019-03-24 17:49 UTC, oliviercailloux approved these changes
Oui.

2019-03-24 17:51 UTC, merged