Première itération
hamzaoui-Hmz/Collaborative-exams pull request #17
Opened 2019-03-16 16:14 UTC by boukalaamine

@oliviercailloux please review

2019-03-17 09:39 UTC, oliviercailloux commented
Veuillez activer les issues sur votre GitHub SVP.

2019-03-17 10:21 UTC, oliviercailloux requested changes
Commentaires sur reste de la hiérarchie similaires au reste.

2019-03-17 10:21 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/collaborative_exams/model/entity/question/IQuestion.java
> + * Question is immuable
immutable, en anglais

2019-03-17 10:21 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/collaborative_exams/model/entity/question/IQuestion.java
> +	public String getLanguage();
Utiliser des types spécifiques, et s’appuyer sur l’existant, là où c’est possible.
Il faut éviter de se retrouver dans la bd avec des questions en langue "français", d’autres "Français", d’autres "Francais", "Frensai", "French", "french", etc. On ne pourra rien faire avec de telles informations.
Il serait approprié de renvoyer une Locale, et idéalement, de garantir qu’elle utilise un code iso approprié. http://www.oracle.com/us/technologies/java/locale-140624.html.

Si trop compliqué pour être fait rapidement, se contenter de mettre un TODO à ce propos dans la javadoc ici.

2019-03-17 10:21 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/collaborative_exams/model/entity/question/IQuestion.java
> +	 * @return Person not null and immuable.
Inutile de préciser l’immuabilité ici : une personne est toujours immuable, c’est garanti par la classe elle-même. Sinon, par cohérence, il faudrait le préciser partout où on utilise ce type.

2019-03-17 10:21 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/collaborative_exams/model/entity/question/IQuestion.java
> +	public Person getAuthor();
Supprimer toutes les lignes blanches entre les en-têtes de méthodes et les commentaires javadoc associés.

2019-03-17 10:21 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/collaborative_exams/model/entity/question/IQuestion.java
> +	public boolean equals(Question question);
Commentaire ne correspond pas à l’en-tête.

2019-03-17 10:21 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/collaborative_exams/model/entity/question/FreeQuestion.java
> + * Question is immuable
Une doc approximative est pire que pas de doc, car on ne sait pas si on peut s’y fier. Il ne s’agit pas de `Question` ici.

2019-03-17 10:21 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/collaborative_exams/model/entity/question/FreeQuestion.java
> +	private String language;
C’est une bonne chose que `phrasing` soit final, mais alors, par cohérence, il faudrait que les autres champs (t.q. language) le soient aussi.

2019-03-17 10:21 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/collaborative_exams/model/entity/question/FreeQuestion.java
> +	private boolean isCorrect;
Champ inutile sur `FreeQuestion`, utile sur les types TF ou YN. C’est à ça qu’est censé servir l’héritage : définir les méthodes seulement là où elles sont censées.
En outre, un `boolean` ne peut pas être `null`.

2019-03-17 10:21 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/collaborative_exams/model/entity/question/FreeQuestion.java
> +	private Answer answer;
“We consider that a free question ”… ? Oui ?
Même remarque que pour `isCorrect` : `answer` inapproprié sur `FreeQuestion`.

2019-03-17 10:21 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/collaborative_exams/model/entity/question/FreeQuestion.java
> +	}
Ce constructeur détruit toutes vos garanties. Par exemple, la doc affirme que `author` n’est pas `null`, mais cela ne peut pas être vrai après avoir invoqué ce constructeur.

2019-03-17 10:21 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/collaborative_exams/model/entity/question/FreeQuestion.java
> +			throws Exception {
Ne pas annoncer que cette méthode peut envoyer une `Exception`. Ce n’est pas vrai en l’occurrence ; le type est bien trop général pour que l’annonce soit utile ; et cela ennuiera systématiquement les utilisateurs de la méthode.

2019-03-17 10:21 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/collaborative_exams/model/entity/question/FreeQuestion.java
> +	}
Intéressant…
Il vaudrait nettement mieux effacer ces deux méthodes #equals que laisser du code qui ne fonctionne pas et qui introduira des bugs subtils si qqn tente de les utiliser (éventuellement sans même s’en rendre compte).

2019-03-19 13:23 UTC, boukalaamine commented
@oliviercailloux Please review the new commit

2019-03-20 06:37 UTC, oliviercailloux commented
Avez-vous lu mon commentaire https://github.com/hamzaoui-Hmz/Collaborative-exams/pull/17#issuecomment-473649229 ?

2019-03-20 07:10 UTC, oliviercailloux requested changes
Je n’ai pas l’impression que tous mes commentaires aient été pris en compte, par exemple celui sur la langue de la question, et voir reste des commentaires de cette review.

2019-03-20 07:10 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/collaborative_exams/model/entity/question/MCQuestion.java
> +	public boolean equals(MCQuestion question) {
Toujours incorrect. Il faut surcharger #hashcode, pour une implémentation correcte. Et on s’attend à ce que equals soit surchargé pour toutes les classes (expl, TrueFalseQuestion) ou pour aucune.

2019-03-20 07:10 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/collaborative_exams/model/entity/question/MCQuestion.java
> +			throws Exception {
Éviter de balancer le type trop général `Exception`, préférer des types plus spécifiques et donc plus informatifs.

2019-03-20 07:10 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/collaborative_exams/model/entity/question/TrueFalseQuestion.java
> +	public TrueFalseQuestion()
Je n’ai pas l’impression que mon commentaire sur les constructeurs vides ait été pris en compte.

2019-03-20 07:10 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/collaborative_exams/model/entity/question/YesNoQuestion.java
> +			throws Exception {
Je ne vois pas l’avantage de choisir les réponses ici. Au contraire, ça introduit un risque, puisque les réponses fournies pourraient ne pas être celles prévues. Une YesNoQuestion a deux réponses fixes. Il faut simplement dans le constructeur préciser laquelle est la réponse correcte. Un boolean pourrait fonctionner. (Plus élégant serait deux constructeurs (« factory methods ») statiques, mais vu que le temps presse je n’insisterai pas là-dessus.)

2019-03-20 07:10 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/collaborative_exams/model/entity/question/YesNoQuestion.java
> +		return null;
Il serait sympathique pour vos utilisateurs de garantir (et de documenter), au contraire, que `null` n’est jamais renvoyé.

2019-03-20 07:10 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/collaborative_exams/model/entity/question/MCQuestion.java
> +public class MCQuestion implements IQuestion {
Je ne vois pas où on peut récupérer les réponses correctes sur `MCQuestion` ?

2019-03-20 07:10 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/collaborative_exams/model/entity/question/MCQuestion.java
> +	public boolean equals(MCQuestion question) {
Vu les délais, à mon avis mieux vaudrait abandonner cet aspect et éviter de surcharger equals tout simplement, à moins que vous ne pensiez être capable de l’implémenter correctement très rapidement. Il serait bien de l’avoir mais ça ne me semble pas essentiel à ce stade.

2019-03-22 15:19 UTC, boukalaamine commented
@oliviercailloux  Concernant les constructeurs vides, à chaque fois que je les retire, j'ai des erreurs de compilations.

Après avoir cherché un peu partout, il semblerait que ce soit lié au compilateur. Je ne suis pas le seul à être dans cette situation, certains de mes camarades me l'ont confirmé.

2019-03-22 15:21 UTC, boukalaamine commented
@oliviercailloux L'information pour savoir si une question est correcte se trouve au niveau de la classe Answer et plus précisement dans l'attribut de type boolean "isCorrect".

2019-03-22 15:25 UTC, boukalaamine commented
@oliviercailloux 

Dois-je continuer à travailler sur ma 1ère itération étant donné qu'elle est sur 2 points et que nous ne sommes pas très loin de la modélisation souhaitée, ou je la laisse tomber vu les délais ?

2019-03-22 17:25 UTC, oliviercailloux approved these changes

2019-03-22 17:26 UTC, oliviercailloux commented
Arrêtons-nous là effectivement pour cette première itération, afin d’être à l’heure pour la deuxième.

2019-03-22 17:40 UTC, merged