2eme iteration
hamzaoui-Hmz/Collaborative-exams pull request #19
Opened 2019-03-21 10:49 UTC by boumaza-khaled

@oliviercailloux  Please review 
Veuillez prendre en considération cette demande et pas celle faite hier ... 
J'ai produit ce qui a été demandé dans la 1ere itération, mais je voudrais s'il vous plait que vous considériez cela comme étant ma 2eme itération.

2019-03-22 09:39 UTC, oliviercailloux requested changes

2019-03-22 09:39 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/collaborative_exams/model/entity/question/QuestionPhrasing.java
> +    public void setTopic(String topic) {
Il serait plus simple que cet objet soit immuable. Par ailleurs, j’imagine que ce que vous appelez “topic” est en fait l’énoncé de la question, auquel cas il faut l’appeler “phrasing”.

2019-03-22 09:39 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/collaborative_exams/model/entity/question/QuestionPhrasing.java
> +        }
Il vaudrait nettement mieux s’assurer que la liste n’est jamais nulle.

2019-03-22 09:39 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/collaborative_exams/model/entity/question/Stats.java
> + */
Ce commentaire est-il vraiment utile ?

2019-03-22 09:39 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/collaborative_exams/model/entity/question/Stats.java
> +    //compteur qui s'incremente de 1 chaque choix que cette reponse participe a un QCM
Anglais SVP.
Le compteur ne s’incrémente pas tout seul.
Vous voulez dire, j’imagine, que ceci compte le nombre de participations de la question à un QCM.

2019-03-22 09:39 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/collaborative_exams/model/entity/question/Stats.java
> +    public Stats() {
Objet à rendre immuable également. Supprimer les constructeurs inutiles (seul le dernier est utile).

2019-03-22 09:39 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/collaborative_exams/model/entity/question/Exam.java
> +public class Exam implements Serializable {
Un Exam doit être lié à un auteur, et être immuable. Il doit avoir un nom, qui devrait remplacer topic.

2019-03-22 09:39 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/collaborative_exams/Service/AnswerQuestionService.java
> +            // un condidat a selectionné une reponse Fausse, alors on augmante le membre de selection de 1
In english, please.

2019-03-22 09:39 UTC, oliviercailloux commented on src/test/java/io/github/oliviercailloux/collaborative_exams/helper/QuestionTest.java
> +//	 @Test
Veuillez restaurer ce test et modifier ce qui doit l’être pour qu’il passe, sauf si c’est extrêmement compliqué (expliquer dans ce cas).

2019-03-22 09:39 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/collaborative_exams/Service/ExamService.java
> +                    if (em != null) {
Ceci masque les problèmes, à modifier.

2019-03-22 14:27 UTC, boumaza-khaled commented on src/main/java/io/github/oliviercailloux/collaborative_exams/model/entity/question/Stats.java
> +    public Stats() {
Si je ne mets pas le constructeur par défaut " public Stats() " l'IDE me sort un Warning

2019-03-22 14:30 UTC, boumaza-khaled commented on src/main/java/io/github/oliviercailloux/collaborative_exams/model/entity/question/Stats.java
> +    public Stats() {
Je ne vois pas comment la class Stats puisse etre Immuable vu qu'elle doit changer pour compter les stats

2019-03-22 14:33 UTC, boumaza-khaled commented on src/main/java/io/github/oliviercailloux/collaborative_exams/model/entity/question/QuestionPhrasing.java
> +    public void setTopic(String topic) {
ok

2019-03-22 14:35 UTC, boumaza-khaled commented on src/main/java/io/github/oliviercailloux/collaborative_exams/model/entity/question/QuestionPhrasing.java
> +        }
ok

2019-03-22 14:38 UTC, boumaza-khaled commented on src/main/java/io/github/oliviercailloux/collaborative_exams/model/entity/question/Stats.java
> + */
ok

2019-03-22 14:38 UTC, boumaza-khaled commented on src/main/java/io/github/oliviercailloux/collaborative_exams/model/entity/question/Stats.java
> +    //compteur qui s'incremente de 1 chaque choix que cette reponse participe a un QCM
ok

2019-03-22 14:44 UTC, boumaza-khaled commented on src/main/java/io/github/oliviercailloux/collaborative_exams/model/entity/question/Exam.java
> +public class Exam implements Serializable {
ok

2019-03-22 14:44 UTC, boumaza-khaled commented on src/main/java/io/github/oliviercailloux/collaborative_exams/Service/AnswerQuestionService.java
> +            // un condidat a selectionné une reponse Fausse, alors on augmante le membre de selection de 1
ok

2019-03-22 15:12 UTC, boumaza-khaled commented on src/main/java/io/github/oliviercailloux/collaborative_exams/Service/ExamService.java
> +                    if (em != null) {
la EM est gérée par le conteneur, dans le test le serveur ne démarre pas (sauf avec arquillian), d'autre par, je ne veux pas que les testes touches a l’intégrité de la BDD

2019-03-22 16:25 UTC, boumaza-khaled commented on src/test/java/io/github/oliviercailloux/collaborative_exams/helper/QuestionTest.java
> +//	 @Test
Ceci est un teste pour la questionXml cela n'a aucun impact sur ma partie (du moins pour l'instant)

2019-03-22 17:42 UTC, boumaza-khaled commented
@oliviercailloux Please review

2019-03-24 17:46 UTC, oliviercailloux commented
Résoudre conflits d’abord SVP.

2019-03-25 14:36 UTC, boumaza-khaled commented
@oliviercailloux  Please review

2019-03-25 17:08 UTC, oliviercailloux requested changes
À ce stade, concentrons-nous sur les deux points les plus importants.

2019-03-25 17:08 UTC, oliviercailloux commented on src/test/java/io/github/oliviercailloux/collaborative_exams/helper/QuestionTest.java
> +//	 @Test
Je ne comprends pas votre réponse. Ma demande est de ne pas supprimer ce test écrit par vos collègues. C’est important pour ne pas faire reculer le projet.

2019-03-25 17:08 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/collaborative_exams/Service/ExamService.java
> +                    if (em != null) {
Cette logique ne convient pas. Si l’em est null pour cause par exemple d’un problème de configuration, la méthode échouera silencieusement, des données seront perdues et le débuggage sera très difficile.
Il faut que la persistence soit désactivée à la demande lorsqu’on est dans le cas d’un test, pas sur simple condition que l’em soit nul.

2019-03-26 11:02 UTC, boumaza-khaled commented on src/test/java/io/github/oliviercailloux/collaborative_exams/helper/QuestionTest.java
> +//	 @Test
Nous avons vu ensemble le test avec @hamzaoui-Hmz et ceci bloc mon travail, ceci est compliqué a résoudre pour  moi, je bloque depuis hier soir, je ne trouve pas de solution.
Donc pour un premier temps, je fais un escape test pour que me validiez mon travail avant la limite, mais je continu d'essayer de le résoudre.

2019-03-26 11:15 UTC, boumaza-khaled commented
@oliviercailloux please review

2019-03-26 17:40 UTC, boumaza-khaled commented on src/test/java/io/github/oliviercailloux/collaborative_exams/helper/QuestionTest.java
> +//	 @Test
@oliviercailloux  Monsieur, finalement le test est passé... :D :D :D 😋

2019-03-27 12:05 UTC, boumaza-khaled commented
@oliviercailloux  please review

2019-03-27 17:54 UTC, oliviercailloux approved these changes

2019-03-27 22:21 UTC, merged