Implémentation du servlet NewQuestion
hamzaoui-Hmz/Collaborative-exams pull request #20
Opened 2019-03-22 19:52 UTC by boukalaamine

@oliviercailloux please review

2019-03-24 17:53 UTC, oliviercailloux commented
Résoudre build Travis et conflits SVP.

2019-03-24 21:42 UTC, boukalaamine commented
@oliviercailloux Build success and no conflicts

2019-03-25 17:37 UTC, oliviercailloux requested changes
Je suis un peu perdu. Pouvez-vous me résumer vos contributions ? Que voulez-vous faire exactement, et où sont les changements principaux ? En particulier, je ne vois pas le servlet attendu décrit dans le cahier des charges (new question).

2019-03-25 17:37 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/collaborative_exams/Service/IQuestionService.java
> +		em.persist(question);
Ne pas rendre l’auteur persistant à la main en cas de besoin, s’appuyer sur JPA pour gérer ce cas automatiquement pour vous.

2019-03-25 17:37 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/collaborative_exams/Service/IQuestionService.java
> +			throw new Exception("Aucune question correspondante.");
Exception est trop générale, utiliser des exceptions plus précises. IllegalArgumentException conviendrait ici.

2019-03-25 17:37 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/collaborative_exams/controller/NewQuestion.java
> +	public void addQuestion(MultivaluedMap<String, String> form, @CookieParam("authorId") Cookie cookie)
Ce n’est pas ce qui est demandé.

2019-03-25 17:37 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/collaborative_exams/controller/NewQuestionJson.java
> +import io.github.oliviercailloux.collaborative_exams.model.entity.question.IQuestion;
Modification non pertinente.

2019-03-25 17:37 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/collaborative_exams/helper/QuestionText.java
> +	public static <T> String ObjectToJson(List<T> object) throws Exception {
objectsToJson. Respecter le standard Java (l’autre méthode est mal nommée).

2019-03-25 17:37 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/collaborative_exams/model/entity/Language.java
> +
Warnings Eclipse. (Voir tools.)
Utiliser le mécanisme pour convertir un string dans l’enum correspondant, ne pas lister tous les cas à la main.

2019-03-25 17:37 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/collaborative_exams/model/entity/question/FreeQuestion.java
> +		answers.add(this.answer);
Ne pas renvoyer null. Ne pas modifier les réponses dans une méthode qui s’appelle getAnswers. Mais surtout, pourquoi n’utilisez-vous pas getPropositions, déjà codé ? (En l’améliorant au passage, idéalement.)

2019-03-25 17:37 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/collaborative_exams/model/entity/question/MCQuestion.java
> +		// TODO Auto-generated method stub
Pourquoi ce duplicat ?

2019-03-25 19:34 UTC, boukalaamine commented
@oliviercailloux 
Mes contributions dans cette itérations s'articsulent essentiellement autour des Servlets NewQuestion et GetQuestion.

J'ai travaillé sur l'adaptation de ces derniers à la nouvelle modélisation fournie dans la première itération.

Bien entendu, J'ai aussi travaillé sur les services permettant d'effectuer des transactions en JPA (IQuestionService) par exemple.

En résumé, il faut surtout prendre en compte NewQuestion et GetQuestion.

Je prends en compte l'ensemble de vos remarques pour espérer une validation dans les délais.

Je compte raccorder tout cela à une interface graphique si la validation se fait dans les temps.

2019-03-25 21:14 UTC, boukalaamine commented
@oliviercailloux Commentaires pris en compte

2019-03-27 18:08 UTC, oliviercailloux commented
Je n’ai pas l’impression que toutes mes remarques aient été prises en compte. Par ailleurs, avez-vous testé votre servlet en lui envoyant effectivement du Json ? Je ne vois pas comment il peut fonctionner alors qu’il attend un formulaire en paramètre.

2019-03-27 20:24 UTC, boukalaamine commented
@oliviercailloux  Mon code a été testé avec des @QueryParam("").

J'ai livré une version avec form afin de préparer la prochaine itération, à savoir intégrer une interface graphique à l'aide d'un formulaire HTML (j'en ai déjà fait un au tout début avant la validation du cahier des charges sur la gestion des auteurs)

Je peux revenir sur la version avec les @QueryParam(""), si vous le souhaitez mais cela va me ralentir dans mon travail et ça serait inutile de rebrouser chemin.

Concernant vos remarques, j'ai pris en compte la plupart, mais j'attends de pouvoir raccorder le tout à une interface pour avoir les idées claires.

2019-03-27 21:24 UTC, oliviercailloux requested changes
C’est du JSON qui est demandé en entrée dans l’énoncé. Je m’attends à ce que votre HTML produise du JSON, c’est facile avec Javascript.

2019-03-27 21:24 UTC, oliviercailloux commented on questionTest.xml
> +<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
Ce fichier n’a pas un nom unique. BP ressources et cours Search path.

2019-03-27 21:37 UTC, oliviercailloux requested changes

2019-03-27 21:37 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/collaborative_exams/helper/IQuestionText.java
> +	public static <T> T jsonToObject(Class<T> className, String json) throws Exception {
Il serait sympathique de respecter l’ordre des paramètres auxquels un utilisateur de json sera habitué (json puis classname et non l’inverse).

2019-03-27 22:54 UTC, boukalaamine commented
@oliviercailloux Please review changes.

2019-03-28 10:22 UTC, oliviercailloux requested changes

2019-03-28 10:22 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/collaborative_exams/controller/NewQuestionJson.java
> +		return IQuestionText.questionToJson(question);
Le servlet doit retourner l’id, n’est-ce pas ? Ce n’est pas ce qu’il semble faire.

2019-03-28 10:22 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/collaborative_exams/controller/NewQuestionJson.java
>  	public String addBook(JsonObject questionJson) throws Exception {
Pourquoi addBook ?

2019-03-28 10:22 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/collaborative_exams/controller/NewQuestion.java
>  	public String addQuestion(MultivaluedMap<String, String> form, @CookieParam("authorId") Cookie cookie)
L’annotation (json) n’a pas l’air conforme à l’attente (form). Il me semble qu’il convient d’effacer ceci, redondant avec l’autre qui accepte effectivement du json, pour diminuer le nombre de servlets à maintenir dans votre projet.

2019-03-28 11:41 UTC, boukalaamine commented
@oliviercailloux  Commentaires pris en compte.

J'espère que cette version répond à vos attentes afin que je puisse faire le merge et qu'elle puisse être utilisable par tout le monde.

2019-03-28 16:14 UTC, oliviercailloux approved these changes

2019-03-29 07:41 UTC, merged