reformulation de ma 3eme fonctionnlaité
hamzaoui-Hmz/Collaborative-exams pull request #23
Opened 2019-03-28 21:02 UTC by KatiaSersour

@oliviercailloux please review
Après échange avec les membres de mon groupe, j'ai reformuler ma fonctionnalité comme indiqué dans le README.
Merci d'avance pour votre réponse.

2019-03-29 18:16 UTC, oliviercailloux approved these changes

2019-03-29 18:18 UTC, oliviercailloux commented
Noter que un simple servlet GET à ce stade du projet ne représente que 0,4 pts diff, car j’imagine qu’il suffit de copier la structure d’autres servlets existants dans le projet. (Si je me trompe et que la fct requiert plus de subtilités, cela augmente bien sûr le nb de pts diff.)

2019-03-30 10:26 UTC, KatiaSersour commented
@oliviercailloux please review
Je tiens aussi à vous informer que ce servlet n'existait pas et qu'il ne s'agit pas d'un copier coller.
Je souhaiterais avoir vos retours, et si vous pensez toujours que cela ne vaut pas 1 point, je compléterai l'écart.
Merci d'avance.

2019-03-30 22:50 UTC, oliviercailloux requested changes
Code clair et semble fonctionnel. Mais performance terriblement mauvaise.
Merci de remplacer par une requête SQL (enfin, JQL) qui trouve directement les questions adéquates.

Je maintiens que le servlet a exactement la même structure que d’autres existant dans votre projet (que vous-même avez fournis, d’ailleurs !), pour ce qui concerne les interactions avec le conteneur. Cela ira un peu mieux avec la formulation d’une requête JQL correcte, puisque c’est effectivement quelque chose de nouveau.

Pour compléter votre pt diff, vous pourriez envisager de compléter une partie de l’implémentation de PersonalTags dans l’énoncé original, https://github.com/oliviercailloux/projets/blob/master/EE/Collaborative%20exams.adoc (mais je n’ai pas vérifié si c’est déjà dans le code actuel, mais je ne pense pas).

2019-03-30 22:50 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/collaborative_exams/controller/QuestionByTag.java
> +	public List<Question> getQuestions(@QueryParam("idAuthor") Integer idAuthor, @QueryParam("tag") String tag)throws Exception {
int serait mieux que Integer, pour afficher clairement qu’un null n’est pas admis ici.

2019-04-02 14:43 UTC, KatiaSersour commented
@oliviercailloux  please review

2019-04-02 16:30 UTC, oliviercailloux requested changes

2019-04-02 16:30 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/collaborative_exams/Service/QuestionService.java
> +		Query query = em.createQuery("SELECT q FROM PersonTag pt JOIN pt.question q WHERE pt.tag = :tag and pt.author = :author");
Warnings Eclipse. BP Style.

2019-04-02 16:30 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/collaborative_exams/controller/GetPersonalTag.java
> +	public String getPersonalTag(@QueryParam("idQuestion") int idQuestion) throws Exception {
Pas de throws Exception, trop général.

2019-04-03 12:35 UTC, KatiaSersour commented
@oliviercailloux please review

2019-04-03 21:03 UTC, oliviercailloux approved these changes

2019-04-03 21:34 UTC, merged