Amine it3
hamzaoui-Hmz/Collaborative-exams pull request #25
Opened 2019-03-30 22:11 UTC by boukalaamine

@oliviercailloux 

Dans cette troisième itération, je m'occupe comme indiqué dans mon cahier des charges de la relation SameAbility.

J'aimerais me faire valider dans un premier temps cette fonctionnalité et si j'ai le temps, je souhaiterais faire aussi delete SameAbilityServlet afin de donner une suite logique à mes travaux.

2019-03-31 09:10 UTC, oliviercailloux commented
This branch has conflicts that must be resolved

2019-04-01 09:26 UTC, boukalaamine commented
@oliviercailloux Conflicts resolved

2019-04-01 14:04 UTC, oliviercailloux requested changes

2019-04-01 14:04 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/collaborative_exams/model/entity/SameAbility.java
> +	/*public boolean isSameAbility(Question q1, Question q2) {
Vous avez raison, elle n’est pas bonne. À effacer !

2019-04-01 14:04 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/collaborative_exams/model/entity/SameAbility.java
> +		 * L'id de la première question est forcément plus petit que celui de la deuxième question car les objets SameAbility ont été ajoutés de la sorte.
Commentaire à retirer ou déplacer, car votre méthode equals fonctionne indépendamment de cette hypothèse (ce qui est heureux).

2019-04-01 14:04 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/collaborative_exams/model/entity/SameAbility.java
> +			return false;
Quelle horreur. Utiliser Objects.equals.

2019-04-01 14:04 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/collaborative_exams/model/entity/SameAbility.java
> +	public boolean equals(SameAbility obj) {
Il faut plus généralement surcharger equals(Object) et hashcode(Object).

2019-04-01 14:04 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/collaborative_exams/model/entity/SameAbility.java
> -	public boolean isSameAbility(Question q1, Question q2) {
Il semble pertinent de vérifier dans le constructeur que q1 est d’id inférieur à q2, et de documenter plus généralement ce fait (sur les getters et sur la classe).

2019-04-01 14:04 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/collaborative_exams/controller/NewSameAbility.java
> +	@Consumes(MediaType.TEXT_PLAIN)
Ce n’est pas vrai, votre méthode ne `Consumes` rien du tout.

2019-04-01 14:04 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/collaborative_exams/controller/NewSameAbility.java
>  			throw new Exception("the question id :" + idQuestion1 + "is null.");
Ne pas lancer des exceptions aussi générales. Et le message est incorrect. (Je sais que cette ligne de code pré-existait, mais ce n’est pas une raison.)

2019-04-01 14:04 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/collaborative_exams/controller/NewSameAbility.java
> +		}
- Formater le code pour suivre les conventions habituelles.
- Éviter cette répétition inélégante. Affecter d’abord q1 et q2 dans le bon ordre, puis invoquer le même code une seule fois.

2019-04-01 14:04 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/collaborative_exams/controller/NewSameAbility.java
> +		}
À quoi sert SQL ? Effectuer une requête pour savoir si elle existe, au lieu de tout parcourir en mémoire !

2019-04-01 20:21 UTC, boukalaamine commented
@oliviercailloux, j'ai en principe pris en compte tout vos commentaires.

étant donnée l'inutilité de la méthode `equals` dans SameAbility, j'ai décidé de retirer cette méthode de la classe.

Je souhaiterais avancer encore dans mes travaux si cette partie vous convient.

- Faire un servlet pour la deletion
- Faire une interface graphique pour SameAbility

2019-04-02 07:42 UTC, oliviercailloux approved these changes
J’approuve moyennant une petite modification mineure. Je vous fais confiance pour la prendre en compte, inutile de redemander une revue de code après la modif.

2019-04-02 07:42 UTC, oliviercailloux commented on src/main/java/io/github/oliviercailloux/collaborative_exams/Service/SameAbilityService.java
> +		// Car relation réflexive
Coder (et donc aussi commenter) en anglais SVP.

2019-04-02 19:38 UTC, merged